# Generated by Django 5.0.1 on 2024-02-01 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_email', models.CharField(max_length=100)),
                ('employee_address', models.CharField(max_length=200)),
                ('employee_phone', models.CharField(max_length=10)),
                ('employee_about', models.TextField()),
                ('employee_position', models.CharField(choices=[('Manager', 'Manager'), ('Department Head', 'depthead'), ('Software Engineer', 'sftengnr')], max_length=50)),
                ('employee_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
